### WORKFLOW
* DATA PREP
* EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
import neattext.functions as nfx
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity,linear_kernel

In [3]:
df = pd.read_csv('C:/Users/Ashray/Downloads/NLPify-main/NLPify-main/data/udemy2.csv',encoding='latin-1', on_bad_lines='skip')

In [4]:
df

,course_id,course_title,url,is_paid,price,professor,description,num_subscribers,Unnamed: 8,Unnamed: 9,...,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128
0,659368,Deep Learning Prerequisites: Logistic Regressi...,/data-science-logistic-regression-in-python/,True,$120,Lazy Programmer Inc.,"<p>This course is a lead-in to <strong class=""...",8228,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,556954,Deep Learning Prerequisites: Linear Regression...,/data-science-linear-regression-in-python/,True,$120,Lazy Programmer Inc.,<p>This course teaches you about one popular t...,8710,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,43540,Critical Thinker Academy: Learn to Think Like ...,/critical-thinker-academy/,True,$95,Kevin deLaplante,"<p> \t<strong style="""">For long-term success ...",25362,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,116286,Workshop in Probability and Statistics,/statshelp/,True,$40,Dr. George Ingersoll,"<p style=""""> \t This workshop is designed to ...",11505,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1048008,Paul and His Letter to the Ephesians,/paul-and-his-letter-to-the-ephesians/,True,$120,N.T. Wright,<p>Prof. N.T. Wright renowned biblical scholar...,930,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39545,1228316,IELTS Strategic Speaking for Band 7 or Higher,/ielts-strategic-speaking-for-band-7-or-higher/,TRUE,$20,Uthman Bilal,<p>Highlights:</p><ul><li>Tips on achieving Ba...,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39546,1000322,High School Placement Test Math portion. Are y...,/high-school-placement-test-math-portion-are-y...,TRUE,$150,Dr. Harold Saavedra,<p>Welcome to High School Placement Test Math ...,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39547,951238,Pass the CMA Exam #2 the first time- Investm...,/pass-the-cma-exam-2-the-first-time-investment...,TRUE,$20,Dr. John Mclellan,<p>This course is a comprehensive study progra...,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39548,597870,Interview On Cisco ASA Firewall,/interview-on-cisco-asa-firewall/,TRUE,$45,Network Security Secure Metrics,<p>If you are preparing for an interview on CI...,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39549,1223114,GMAT Data Sufficiency-50 Original Questions-So...,/gmat-data-sufficiency-50-original-questions-s...,TRUE,$50,Loony Corn,<p><strong>The Data Sufficiency questions on t...,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

df.shape

(39550, 129)

In [6]:
df.describe()

       Unnamed: 128
count           1.0
mean           43.0
std             NaN
min            43.0
25%            43.0
50%            43.0
75%            43.0
max            43.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39550 entries, 0 to 39549
Columns: 129 entries, course_id to Unnamed: 128
dtypes: float64(1), object(128)
memory usage: 38.9+ MB

In [8]:
df.drop(df.columns[8:], axis=1,inplace=True)

In [9]:
df

,course_id,course_title,url,is_paid,price,professor,description,num_subscribers
0,659368,Deep Learning Prerequisites: Logistic Regressi...,/data-science-logistic-regression-in-python/,True,$120,Lazy Programmer Inc.,"<p>This course is a lead-in to <strong class=""...",8228
1,556954,Deep Learning Prerequisites: Linear Regression...,/data-science-linear-regression-in-python/,True,$120,Lazy Programmer Inc.,<p>This course teaches you about one popular t...,8710
2,43540,Critical Thinker Academy: Learn to Think Like ...,/critical-thinker-academy/,True,$95,Kevin deLaplante,"<p> \t<strong style="""">For long-term success ...",25362
3,116286,Workshop in Probability and Statistics,/statshelp/,True,$40,Dr. George Ingersoll,"<p style=""""> \t This workshop is designed to ...",11505
4,1048008,Paul and His Letter to the Ephesians,/paul-and-his-letter-to-the-ephesians/,True,$120,N.T. Wright,<p>Prof. N.T. Wright renowned biblical scholar...,930
...,...,...,...,...,...,...,...,...
39545,1228316,IELTS Strategic Speaking for Band 7 or Higher,/ielts-strategic-speaking-for-band-7-or-higher/,TRUE,$20,Uthman Bilal,<p>Highlights:</p><ul><li>Tips on achieving Ba...,0
39546,1000322,High School Placement Test Math portion. Are y...,/high-school-placement-test-math-portion-are-y...,TRUE,$150,Dr. Harold Saavedra,<p>Welcome to High School Placement Test Math ...,0
39547,951238,Pass the CMA Exam #2 the first time- Investm...,/pass-the-cma-exam-2-the-first-time-investment...,TRUE,$20,Dr. John Mclellan,<p>This course is a comprehensive study progra...,0
39548,597870,Interview On Cisco ASA Firewall,/interview-on-cisco-asa-firewall/,TRUE,$45,Network Security Secure Metrics,<p>If you are preparing for an interview on CI...,0
39549,1223114,GMAT Data Sufficiency-50 Original Questions-So...,/gmat-data-sufficiency-50-original-questions-s...,TRUE,$50,Loony Corn,<p><strong>The Data Sufficiency questions on t...,0

In [10]:
df.dtypes

course_id          object
course_title       object
url                object
is_paid            object
price              object
professor          object
description        object
num_subscribers    object
dtype: object

In [11]:
df.isnull().sum()

course_id          1
course_title       1
url                5
is_paid            5
price              5
professor          5
description        5
num_subscribers    9
dtype: int64

In [12]:
df.columns

Index(['course_id', 'course_title', 'url', 'is_paid', 'price', 'professor',
       'description', 'num_subscribers'],
      dtype='object')

### EDA on SUbscribers

In [13]:
df.head()

,course_id,course_title,url,is_paid,price,professor,description,num_subscribers
0,659368,Deep Learning Prerequisites: Logistic Regressi...,/data-science-logistic-regression-in-python/,True,$120,Lazy Programmer Inc.,"<p>This course is a lead-in to <strong class=""...",8228
1,556954,Deep Learning Prerequisites: Linear Regression...,/data-science-linear-regression-in-python/,True,$120,Lazy Programmer Inc.,<p>This course teaches you about one popular t...,8710
2,43540,Critical Thinker Academy: Learn to Think Like ...,/critical-thinker-academy/,True,$95,Kevin deLaplante,"<p> \t<strong style="""">For long-term success ...",25362
3,116286,Workshop in Probability and Statistics,/statshelp/,True,$40,Dr. George Ingersoll,"<p style=""""> \t This workshop is designed to ...",11505
4,1048008,Paul and His Letter to the Ephesians,/paul-and-his-letter-to-the-ephesians/,True,$120,N.T. Wright,<p>Prof. N.T. Wright renowned biblical scholar...,930

In [14]:
df.isnull().sum()

course_id          1
course_title       1
url                5
is_paid            5
price              5
professor          5
description        5
num_subscribers    9
dtype: int64

In [15]:

df['course_title']

0        Deep Learning Prerequisites: Logistic Regressi...
1        Deep Learning Prerequisites: Linear Regression...
2        Critical Thinker Academy: Learn to Think Like ...
3                   Workshop in Probability and Statistics
4                     Paul and His Letter to the Ephesians
                               ...
39545        IELTS Strategic Speaking for Band 7 or Higher
39546    High School Placement Test Math portion. Are y...
39547    Pass the CMA Exam #2  the first time-  Investm...
39548                      Interview On Cisco ASA Firewall
39549    GMAT Data Sufficiency-50 Original Questions-So...
Name: course_title, Length: 39550, dtype: object

In [16]:
df['course_title'] = df['course_title'].astype(str)

In [17]:
# Clean text: stopwords
df['Course_title'] = df['course_title'].apply(nfx.remove_stopwords)

In [18]:
df['Course_title'] = df['course_title'].apply(nfx.remove_special_characters)

In [19]:
df[['Course_title','course_title']]

,Course_title,course_title
0,Deep Learning Prerequisites Logistic Regressio...,Deep Learning Prerequisites: Logistic Regressi...
1,Deep Learning Prerequisites Linear Regression ...,Deep Learning Prerequisites: Linear Regression...
2,Critical Thinker Academy Learn to Think Like a...,Critical Thinker Academy: Learn to Think Like ...
3,Workshop in Probability and Statistics,Workshop in Probability and Statistics
4,Paul and His Letter to the Ephesians,Paul and His Letter to the Ephesians
...,...,...
39545,IELTS Strategic Speaking for Band 7 or Higher,IELTS Strategic Speaking for Band 7 or Higher
39546,High School Placement Test Math portion Are yo...,High School Placement Test Math portion. Are y...
39547,Pass the CMA Exam 2 the first time Investmen...,Pass the CMA Exam #2 the first time- Investm...
39548,Interview On Cisco ASA Firewall,Interview On Cisco ASA Firewall
39549,GMAT Data Sufficiency50 Original QuestionsSolv...,GMAT Data Sufficiency-50 Original Questions-So...

In [20]:
df['price'] = df['price'].astype(str)

In [21]:
df['Price'] = df['price'].apply(nfx.remove_special_characters)

In [22]:
df[['Price','price']]

      Price  price
0      120   $120
1      120   $120
2       95    $95
3       40    $40
4      120   $120
...     ...    ...
39545   20    $20
39546  150   $150
39547   20    $20
39548   45    $45
39549   50    $50

[39550 rows x 2 columns]

In [23]:
df.head()

,course_id,course_title,url,is_paid,price,professor,description,num_subscribers,Course_title,Price
0,659368,Deep Learning Prerequisites: Logistic Regressi...,/data-science-logistic-regression-in-python/,True,$120,Lazy Programmer Inc.,"<p>This course is a lead-in to <strong class=""...",8228,Deep Learning Prerequisites Logistic Regressio...,120
1,556954,Deep Learning Prerequisites: Linear Regression...,/data-science-linear-regression-in-python/,True,$120,Lazy Programmer Inc.,<p>This course teaches you about one popular t...,8710,Deep Learning Prerequisites Linear Regression ...,120
2,43540,Critical Thinker Academy: Learn to Think Like ...,/critical-thinker-academy/,True,$95,Kevin deLaplante,"<p> \t<strong style="""">For long-term success ...",25362,Critical Thinker Academy Learn to Think Like a...,95
3,116286,Workshop in Probability and Statistics,/statshelp/,True,$40,Dr. George Ingersoll,"<p style=""""> \t This workshop is designed to ...",11505,Workshop in Probability and Statistics,40
4,1048008,Paul and His Letter to the Ephesians,/paul-and-his-letter-to-the-ephesians/,True,$120,N.T. Wright,<p>Prof. N.T. Wright renowned biblical scholar...,930,Paul and His Letter to the Ephesians,120

In [24]:
df

,course_id,course_title,url,is_paid,price,professor,description,num_subscribers,Course_title,Price
0,659368,Deep Learning Prerequisites: Logistic Regressi...,/data-science-logistic-regression-in-python/,True,$120,Lazy Programmer Inc.,"<p>This course is a lead-in to <strong class=""...",8228,Deep Learning Prerequisites Logistic Regressio...,120
1,556954,Deep Learning Prerequisites: Linear Regression...,/data-science-linear-regression-in-python/,True,$120,Lazy Programmer Inc.,<p>This course teaches you about one popular t...,8710,Deep Learning Prerequisites Linear Regression ...,120
2,43540,Critical Thinker Academy: Learn to Think Like ...,/critical-thinker-academy/,True,$95,Kevin deLaplante,"<p> \t<strong style="""">For long-term success ...",25362,Critical Thinker Academy Learn to Think Like a...,95
3,116286,Workshop in Probability and Statistics,/statshelp/,True,$40,Dr. George Ingersoll,"<p style=""""> \t This workshop is designed to ...",11505,Workshop in Probability and Statistics,40
4,1048008,Paul and His Letter to the Ephesians,/paul-and-his-letter-to-the-ephesians/,True,$120,N.T. Wright,<p>Prof. N.T. Wright renowned biblical scholar...,930,Paul and His Letter to the Ephesians,120
...,...,...,...,...,...,...,...,...,...,...
39545,1228316,IELTS Strategic Speaking for Band 7 or Higher,/ielts-strategic-speaking-for-band-7-or-higher/,TRUE,$20,Uthman Bilal,<p>Highlights:</p><ul><li>Tips on achieving Ba...,0,IELTS Strategic Speaking for Band 7 or Higher,20
39546,1000322,High School Placement Test Math portion. Are y...,/high-school-placement-test-math-portion-are-y...,TRUE,$150,Dr. Harold Saavedra,<p>Welcome to High School Placement Test Math ...,0,High School Placement Test Math portion Are yo...,150
39547,951238,Pass the CMA Exam #2 the first time- Investm...,/pass-the-cma-exam-2-the-first-time-investment...,TRUE,$20,Dr. John Mclellan,<p>This course is a comprehensive study progra...,0,Pass the CMA Exam 2 the first time Investmen...,20
39548,597870,Interview On Cisco ASA Firewall,/interview-on-cisco-asa-firewall/,TRUE,$45,Network Security Secure Metrics,<p>If you are preparing for an interview on CI...,0,Interview On Cisco ASA Firewall,45
39549,1223114,GMAT Data Sufficiency-50 Original Questions-So...,/gmat-data-sufficiency-50-original-questions-s...,TRUE,$50,Loony Corn,<p><strong>The Data Sufficiency questions on t...,0,GMAT Data Sufficiency50 Original QuestionsSolv...,50

In [25]:
df['description'] = df['description'].astype(str)

In [26]:
df['Description'] = df['description'].apply(nfx.remove_special_characters)

In [27]:
df['Description'] = df['description'].apply(nfx.remove_stopwords)

In [28]:
df.isnull().sum()

course_id          1
course_title       0
url                5
is_paid            5
price              0
professor          5
description        0
num_subscribers    9
Course_title       0
Price              0
Description        0
dtype: int64

In [29]:
df = df.drop(['course_title','price','description'],axis=1)

In [30]:
df

,course_id,url,is_paid,professor,num_subscribers,Course_title,Price,Description
0,659368,/data-science-logistic-regression-in-python/,True,Lazy Programmer Inc.,8228,Deep Learning Prerequisites Logistic Regressio...,120,"<p>This course lead-in <strong class=""redactor..."
1,556954,/data-science-linear-regression-in-python/,True,Lazy Programmer Inc.,8710,Deep Learning Prerequisites Linear Regression ...,120,<p>This course teaches popular technique <stro...
2,43540,/critical-thinker-academy/,True,Kevin deLaplante,25362,Critical Thinker Academy Learn to Think Like a...,95,"<p> <strong style="""">For long-term success sch..."
3,116286,/statshelp/,True,Dr. George Ingersoll,11505,Workshop in Probability and Statistics,40,"<p style=""""> workshop designed help sense basi..."
4,1048008,/paul-and-his-letter-to-the-ephesians/,True,N.T. Wright,930,Paul and His Letter to the Ephesians,120,<p>Prof. N.T. Wright renowned biblical scholar...
...,...,...,...,...,...,...,...,...
39545,1228316,/ielts-strategic-speaking-for-band-7-or-higher/,TRUE,Uthman Bilal,0,IELTS Strategic Speaking for Band 7 or Higher,20,<p>Highlights:</p><ul><li>Tips achieving Band ...
39546,1000322,/high-school-placement-test-math-portion-are-y...,TRUE,Dr. Harold Saavedra,0,High School Placement Test Math portion Are yo...,150,<p>Welcome High School Placement Test Math por...
39547,951238,/pass-the-cma-exam-2-the-first-time-investment...,TRUE,Dr. John Mclellan,0,Pass the CMA Exam 2 the first time Investmen...,20,<p>This course comprehensive study program hel...
39548,597870,/interview-on-cisco-asa-firewall/,TRUE,Network Security Secure Metrics,0,Interview On Cisco ASA Firewall,45,<p>If preparing interview CISCO ASA firewall a...
39549,1223114,/gmat-data-sufficiency-50-original-questions-s...,TRUE,Loony Corn,0,GMAT Data Sufficiency50 Original QuestionsSolv...,50,<p><strong>The Data Sufficiency questions GMAT...

In [31]:
df1 = df.dropna(inplace=True)

In [32]:
df

,course_id,url,is_paid,professor,num_subscribers,Course_title,Price,Description
0,659368,/data-science-logistic-regression-in-python/,True,Lazy Programmer Inc.,8228,Deep Learning Prerequisites Logistic Regressio...,120,"<p>This course lead-in <strong class=""redactor..."
1,556954,/data-science-linear-regression-in-python/,True,Lazy Programmer Inc.,8710,Deep Learning Prerequisites Linear Regression ...,120,<p>This course teaches popular technique <stro...
2,43540,/critical-thinker-academy/,True,Kevin deLaplante,25362,Critical Thinker Academy Learn to Think Like a...,95,"<p> <strong style="""">For long-term success sch..."
3,116286,/statshelp/,True,Dr. George Ingersoll,11505,Workshop in Probability and Statistics,40,"<p style=""""> workshop designed help sense basi..."
4,1048008,/paul-and-his-letter-to-the-ephesians/,True,N.T. Wright,930,Paul and His Letter to the Ephesians,120,<p>Prof. N.T. Wright renowned biblical scholar...
...,...,...,...,...,...,...,...,...
39545,1228316,/ielts-strategic-speaking-for-band-7-or-higher/,TRUE,Uthman Bilal,0,IELTS Strategic Speaking for Band 7 or Higher,20,<p>Highlights:</p><ul><li>Tips achieving Band ...
39546,1000322,/high-school-placement-test-math-portion-are-y...,TRUE,Dr. Harold Saavedra,0,High School Placement Test Math portion Are yo...,150,<p>Welcome High School Placement Test Math por...
39547,951238,/pass-the-cma-exam-2-the-first-time-investment...,TRUE,Dr. John Mclellan,0,Pass the CMA Exam 2 the first time Investmen...,20,<p>This course comprehensive study program hel...
39548,597870,/interview-on-cisco-asa-firewall/,TRUE,Network Security Secure Metrics,0,Interview On Cisco ASA Firewall,45,<p>If preparing interview CISCO ASA firewall a...
39549,1223114,/gmat-data-sufficiency-50-original-questions-s...,TRUE,Loony Corn,0,GMAT Data Sufficiency50 Original QuestionsSolv...,50,<p><strong>The Data Sufficiency questions GMAT...

In [33]:
df.isnull().sum()

course_id          0
url                0
is_paid            0
professor          0
num_subscribers    0
Course_title       0
Price              0
Description        0
dtype: int64

In [34]:
df.rename(columns = {'Course_title':'course_title', 'Description':'description','Price':'price'}, inplace = True)

In [35]:
df.head()

,course_id,url,is_paid,professor,num_subscribers,course_title,price,description
0,659368,/data-science-logistic-regression-in-python/,True,Lazy Programmer Inc.,8228,Deep Learning Prerequisites Logistic Regressio...,120,"<p>This course lead-in <strong class=""redactor..."
1,556954,/data-science-linear-regression-in-python/,True,Lazy Programmer Inc.,8710,Deep Learning Prerequisites Linear Regression ...,120,<p>This course teaches popular technique <stro...
2,43540,/critical-thinker-academy/,True,Kevin deLaplante,25362,Critical Thinker Academy Learn to Think Like a...,95,"<p> <strong style="""">For long-term success sch..."
3,116286,/statshelp/,True,Dr. George Ingersoll,11505,Workshop in Probability and Statistics,40,"<p style=""""> workshop designed help sense basi..."
4,1048008,/paul-and-his-letter-to-the-ephesians/,True,N.T. Wright,930,Paul and His Letter to the Ephesians,120,<p>Prof. N.T. Wright renowned biblical scholar...

In [36]:
df['url'] = 'https://www.udemy.com/course' + df['url']

In [37]:
df.to_csv('Udemy_cleaned.csv')

In [38]:
df.head()

,course_id,url,is_paid,professor,num_subscribers,course_title,price,description
0,659368,https://www.udemy.com/course/data-science-logi...,True,Lazy Programmer Inc.,8228,Deep Learning Prerequisites Logistic Regressio...,120,"<p>This course lead-in <strong class=""redactor..."
1,556954,https://www.udemy.com/course/data-science-line...,True,Lazy Programmer Inc.,8710,Deep Learning Prerequisites Linear Regression ...,120,<p>This course teaches popular technique <stro...
2,43540,https://www.udemy.com/course/critical-thinker-...,True,Kevin deLaplante,25362,Critical Thinker Academy Learn to Think Like a...,95,"<p> <strong style="""">For long-term success sch..."
3,116286,https://www.udemy.com/course/statshelp/,True,Dr. George Ingersoll,11505,Workshop in Probability and Statistics,40,"<p style=""""> workshop designed help sense basi..."
4,1048008,https://www.udemy.com/course/paul-and-his-lett...,True,N.T. Wright,930,Paul and His Letter to the Ephesians,120,<p>Prof. N.T. Wright renowned biblical scholar...

In [2]:
%pip install gensim==3.2.0

Requirement already satisfied: gensim==3.2.0 in c:\users\ashray\anaconda3\envs\nlpify\lib\site-packages (3.2.0)
Requirement already satisfied: numpy>=1.11.3 in c:\users\ashray\anaconda3\envs\nlpify\lib\site-packages (from gensim==3.2.0) (1.23.5)
Requirement already satisfied: scipy>=0.18.1 in c:\users\ashray\anaconda3\envs\nlpify\lib\site-packages (from gensim==3.2.0) (1.10.1)
Requirement already satisfied: six>=1.5.0 in c:\users\ashray\anaconda3\envs\nlpify\lib\site-packages (from gensim==3.2.0) (1.16.0)
Requirement already satisfied: smart-open>=1.2.1 in c:\users\ashray\anaconda3\envs\nlpify\lib\site-packages (from gensim==3.2.0) (6.3.0)
Note: you may need to restart the kernel to use updated packages.